baseurl                  = "https://example.com/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "it"
isMultilingual           = false
title                    = "Manuale delle Piante"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"
pluralizeListTitles      = false

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link

# Metadata for Open Graph and Twitter
#    description          = "A new Hugo site."               # Max 160 characters show in search results
#    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
#    title                = "Call me Sam"

[[params.mainMenu]]
    link = "/piante"
    text = "piante"

[[params.mainMenu]]
    link = "/supplementi"
    text = "supplementi"
    
[[params.mainMenu]]
    link = "/tags"
    text = "tags"

[[params.mainMenu]]
    link = "/about/"
    text = "info"

[imaging]
    quality = 75